name: Kamil Biela
description: Coding blog
meta_description: "Writting articles about backend and fronted. Speed up coding by reading my experiences."

aboutPage: false

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://kamilbiela.github.io'
google_analytics: 'UA-45004981-4'
disqus: true
disqus_shortname: 'kamilbiela'

# Details for the RSS feed generator
url:            'http://kamilbiela.github.io'
author:         'Kamil Biela'
authorTwitter:  'kamil_biela'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
